Ft logout
atlp-rwanda/e-commerce-lydia-32-fn pull request #10
Opened 2024-07-03 07:25 UTC by rodriguecyber

implement logout functionalities

2024-07-03 18:26 UTC, Ishimwe7 requested changes, later dismissed
Resolve conflicts

2024-07-04 21:26 UTC, robsdagreat approved these changes
Well done @rodriguecyber . Since the conflicts are resolved, We're good to go.

2024-07-04 21:50 UTC, kirengamartial approved these changes
consider the feedback

2024-07-04 21:50 UTC, kirengamartial commented on src/Components/navbar.tsx
> +      navigate('/')
you have the same 2 navigate in one try and catch you may remove one since there are doing the same thing

2024-07-04 21:50 UTC, kirengamartial commented on src/Components/navbar.tsx
> +      navigate('/');
you may navigate to /login after logout instead of going to the home page

2024-07-05 06:28 UTC, Balinda21 approved these changes
PR is ready to be merged.

2024-07-05 06:47 UTC, rodriguecyber commented on src/Components/navbar.tsx
> +      navigate('/')
> you have the same 2 navigate in one try and catch you may remove one since there are doing the same thing

solved!

2024-07-05 09:34 UTC, merged