Ft test coverage#187570807
atlp-rwanda/e-commerce-lydia-32-fn pull request #13
Opened 2024-07-03 16:25 UTC by Ishimwe7

### What does this PR do?
This Pull Request serves to setup testing environment for our components
### Description of Task to be completed?
1. Setting Jest testing environment.
2. Running some sample tests to see if they can work
### How should this be manually tested?
Inside root directory run **npm run test** and **npm run test:coverage** if you want to see coverage

2024-07-04 10:28 UTC, kirengamartial requested changes
consider the review i gave you and if those photos are not being used in our application you may remove them

2024-07-04 10:28 UTC, kirengamartial commented on coverage/lcov-report/block-navigation.js
> +    // Classes of code we would like to highlight in the file view
remove those comments they are too many

2024-07-04 18:06 UTC, rodriguecyber approved these changes

2024-07-04 21:00 UTC, robsdagreat approved these changes
Everything is good but consider using yarn

2024-07-05 07:04 UTC, Ishimwe7 commented on coverage/lcov-report/block-navigation.js
> +    // Classes of code we would like to highlight in the file view
I think it is not good practice to edit auto-generates files. I didn't write them though.

2024-07-06 06:52 UTC, closed without merging