Have user be able to search a product with different search criterias
atlp-rwanda/e-commerce-lydia-32-fn pull request #19
Opened 2024-07-07 21:25 UTC by robsdagreat

What does this PR do?

Have a user be able to search for a product using different search criterias

Description of Task to be completed?

As a logged in user, he/she is able to search for a product using different criterias like minimum prices and maximum prices, by their names, etc...

  
 How should this be manually tested?

After clicking on the search icon in the navbar , search for a product using the inputs provided.

What are the relevant pivotal tracker stories

#187570829

2024-07-09 13:43 UTC, Ishimwe7 requested changes
Well done @robsdagreat , otherwise consider comments.

2024-07-09 13:43 UTC, Ishimwe7 commented on .env
Please ignore .env

2024-07-09 13:43 UTC, Ishimwe7 commented on src/Components/search.tsx
> +  const [localSearchTerm, setLocalSearchTerm] = useState(searchTerm);
here it's better to user object with all search criterion, instead of initializing many useStates.

2024-07-09 13:46 UTC, robsdagreat commented on src/Components/search.tsx
> +  const [localSearchTerm, setLocalSearchTerm] = useState(searchTerm);
The only reason why I used those states is because I was going to need them later for updating the UI or giving the message response.

2024-07-09 13:49 UTC, Ishimwe7 commented on src/Components/search.tsx
> +  const [localSearchTerm, setLocalSearchTerm] = useState(searchTerm);
Yeah, i got you, but you can also use Object with all search criterion, and modify data on one object instead of many useStates.

2024-07-09 13:50 UTC, Ishimwe7 commented on src/Components/search.tsx
> +  const [localSearchTerm, setLocalSearchTerm] = useState(searchTerm);
Remember to resolve conflicts

2024-07-09 14:11 UTC, robsdagreat commented on src/Components/search.tsx
> +  const [localSearchTerm, setLocalSearchTerm] = useState(searchTerm);
consider it done!

2024-07-10 07:24 UTC, rodriguecyber approved these changes

2024-07-10 07:43 UTC, kirengamartial approved these changes
remove .env from being tracked by git please

2024-07-10 09:13 UTC, robsdagreat commented
> remove .env from being tracked by git please

I corrected it for sure.

2024-07-10 13:27 UTC, DeliceLydia approved these changes

2024-07-10 16:28 UTC, Balinda21 approved these changes
Codes looks ready to be merged!

2024-07-11 06:18 UTC, bahati10 approved these changes
well implemented feature

2024-07-11 08:00 UTC, Ishimwe7 approved these changes
Good job @robsdagreat

2024-07-11 09:07 UTC, merged